name: PushOriginalToEsoUI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: 'v1.6.1'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Pushing
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'CombatMetronome'

      - name: Zip release
        run: 7z a CombatMetronome_${{github.event.inputs.version}}.zip * -xr!*.git* -xr!*Updated.md*

      - name: Push to EsoUI
        id: push
        uses: M0RGaming/Push-To-EsoUI@main
        with:
          EsoUIToken: ${{secrets.ESOUI_API_TOKEN}}
          EsoUIID: 2373
          path: './CombatMetronome/'
          changelog: 'Changelog.txt'
          readme: 'ReadmeOriginal.md'
          version: ${{github.event.inputs.version}}
          artifact: 'CombatMetronome_${{github.event.inputs.version}}.zip'
