name: ESO Addon Dual Release

# Auslöser: Bei einem Pull Request auf die master-Branch von development
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'development'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract API Version and Addon Version
      id: version_info
      run: |
        APIVersion=$(grep -Po '(?<=## APIVersion: )\d+' CombatMetronome.txt)
        AddonVersion=$(grep -Po '(?<=## Version: )[\d.]+' CombatMetronome.txt)
        # Ersetze Punkte durch Unterstriche
        AddonVersionWithUnderscores=$(echo $AddonVersion | sed 's/\./_/g')
        echo "API_VERSION=$APIVersion" >> $GITHUB_ENV
        echo "ADDON_VERSION=$AddonVersion" >> $GITHUB_ENV
        echo "ADDON_VERSION_UNDERSCORES=$AddonVersionWithUnderscores" >> $GITHUB_ENV

    - name: Extract Changelog
      id: changelog
      run: |
        Changelog=$(cat Changelog.txt)
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$Changelog" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.ADDON_VERSION }}
        release_name: Release ${{ env.ADDON_VERSION }}
        body: ${{ env.CHANGELOG }}
        draft: false
        prerelease: false

    # Zip-Datei für Addon ID 2373 (ohne ReadmeUpdated.md)
    - name: Zip Addon Files for Addon ID 2373 (excluding ReadmeUpdated.md)
      run: |
        zip -r CombatMetronome_v${{ env.ADDON_VERSION_UNDERSCORES }}.zip ./CombatMetronome/ --exclude ReadmeUpdated.md

    - name: Upload Addon ID 2373 to ESOUI
      env:
        API_TOKEN: ${{ secrets.ESOUI_API_TOKEN }}
      run: |
        curl -X POST "https://api.esoui.com/addons/update" \
          -H "Authorization: Bearer $API_TOKEN" \
          -F "id=2373" \
          -F "updatefile=@./CombatMetronome_v${{ env.ADDON_VERSION_UNDERSCORES }}.zip" \
          -F "changelog=${{ env.CHANGELOG }}" \
          -F "compatible=$API_VERSION" \
          -F "description=${{ env.DESCRIPTION }}"
    
    # Zip-Datei für Addon ID 3790 (ohne ReadmeOriginal.md)
    - name: Zip Addon Files for Addon ID 3790 (excluding ReadmeOriginal.md)
      run: |
        zip -r CombatMetronome_v${{ env.ADDON_VERSION_UNDERSCORES }}.zip ./CombatMetronome/ --exclude ReadmeOriginal.md

    - name: Upload Addon ID 3790 to ESOUI
      env:
        API_TOKEN: ${{ secrets.ESOUI_API_TOKEN }}
      run: |
        curl -X POST "https://api.esoui.com/addons/update" \
          -H "Authorization: Bearer $API_TOKEN" \
          -F "id=3790" \
          -F "updatefile=@./CombatMetronome_v${{ env.ADDON_VERSION_UNDERSCORES }}.zip" \
          -F "changelog=${{ env.CHANGELOG }}" \
          -F "compatible=$API_VERSION" \
          -F "description=${{ env.DESCRIPTION }}"
